client_abbr <- function(`Sequence Group`) {
  case_when(
    `Sequence Group` == "NGYN (BFCMC)" ~ "Banner Fort Collins Medical Center",
    `Sequence Group` == "NGYN (CFG)" ~ "Centers for Gastroenterology",
    `Sequence Group` == "NGYN (CPMC)" ~ "Colorado Plains Medical Center",
    `Sequence Group` == "NGYN (CRMC)" ~ "Cheyenne Regional Medical Center",
    `Sequence Group` == "NGYN (EMCH)" ~ "East Morgan County Hospital",
    `Sequence Group` == "NGYN (EPMC)" ~ "Estes Park Health Hospital",
    `Sequence Group` == "NGYN (FR DERM)" ~ "Tech Only Clients",
    `Sequence Group` == "NGYN (GRANDVIEW)" ~ "Grandview Hospital",
    `Sequence Group` == "NGYN (HS)" ~ "Melissa Memorial Hospital",
    `Sequence Group` == "NGYN (IMH)" ~ "Ivinson Memorial Hospital",
    `Sequence Group` == "NGYN (JL DERM)" ~ "Tech Only Clients",
    `Sequence Group` == "NGYN (KHS)" ~ "Kimball County Hospital",
    `Sequence Group` == "NGYN (McKee)" ~ "McKee Medical Center",
    `Sequence Group` == "NGYN (MCR)" ~ "Medical Center of the Rockies",
    `Sequence Group` == "NGYN (MHC)" ~ "Memorial Hospital Central",
    `Sequence Group` == "NGYN (MHCC DC)" ~ "Memorial Hospital of Converse County",
    `Sequence Group` == "NGYN (MHN)" ~ "Memorial Hospital North",
    `Sequence Group` == "NGYN (NCMC)" ~ "North Colorado Medical Center",
    `Sequence Group` == "NGYN (OCH)" ~ "Ogallala Community Hospital",
    `Sequence Group` == "NGYN (PCMH)" ~ "Platte County Memorial Hospital",
    `Sequence Group` == "NGYN (PEAK)" ~ "Summit Pathology Outpatient",
    `Sequence Group` == "NGYN (PVH)" ~ "Poudre Valley Hospital",
    `Sequence Group` == "NGYN (RAWLINS)" ~ "Memorial Hospital of Carbon County",
    `Sequence Group` == "NGYN (SRMC)" ~ "Sterling Regional Medical Center",
    `Sequence Group` == "NGYN (TORRINGTON)" ~ "Torrington Community Hospital",
    `Sequence Group` == "NGYN (UCHGH)" ~ "Greeley Hospital",
    `Sequence Group` == "NGYN (WOODLAND)" ~ "Pikes Peak Regional Hospital",
    `Sequence Group` == "NGYN (WY VA)" ~ "Wyoming Veterans Administration",
    `Sequence Group` == "NGYN OP (MHN)" ~ "Memorial Outpatient",
    `Sequence Group` == "NGYN OP (SP)" ~ "Summit Pathology Outpatient",
    `Sequence Group` == "NGYN OP (SPWY)" ~ "Summit Pathology Outpatient",
    `Sequence Group` == "SURG (BFCMC)" ~ "Banner Fort Collins Medical Center",
    `Sequence Group` == "SURG (CFG)" ~ "Centers for Gastroenterology",
    `Sequence Group` == "SURG (CPMC)" ~ "Colorado Plains Medical Center",
    `Sequence Group` == "SURG (CRMC)" ~ "Cheyenne Regional Medical Center",
    `Sequence Group` == "SURG (EMCH)" ~ "East Morgan County Hospital",
    `Sequence Group` == "SURG (EPMC)" ~ "Estes Park Health Hospital",
    `Sequence Group` == "SURG (FR DERM)" ~ "Tech Only Clients",
    `Sequence Group` == "SURG (GRANDVIEW)" ~ "Grandview Hospital",
    `Sequence Group` == "SURG (HS)" ~ "Melissa Memorial Hospital",
    `Sequence Group` == "SURG (IMH)" ~ "Ivinson Memorial Hospital",
    `Sequence Group` == "SURG (JL DERM)" ~ "Tech Only Clients",
    `Sequence Group` == "SURG (KHS)" ~ "Kimball County Hospital",
    `Sequence Group` == "SURG (McKee)" ~ "McKee Medical Center",
    `Sequence Group` == "SURG (MCR)" ~ "Medical Center of the Rockies",
    `Sequence Group` == "SURG (MHC)" ~ "Memorial Hospital Central",
    `Sequence Group` == "SURG (MHCC DC)" ~ "Memorial Hospital of Converse County",
    `Sequence Group` == "SURG (MHN)" ~ "Memorial Hospital North",
    `Sequence Group` == "SURG (NCMC)" ~ "North Colorado Medical Center",
    `Sequence Group` == "SURG (OCH)" ~ "Ogallala Community Hospital",
    `Sequence Group` == "SURG (PCMH)" ~ "Platte County Memorial Hospital",
    `Sequence Group` == "SURG (PEAK)" ~ "Summit Pathology Outpatient",
    `Sequence Group` == "SURG (PVH)" ~ "Poudre Valley Hospital",
    `Sequence Group` == "SURG (RAWLINS)" ~ "Memorial Hospital of Carbon County",
    `Sequence Group` == "SURG (SRMC)" ~ "Sterling Regional Medical Center",
    `Sequence Group` == "SURG (TORRINGTON)" ~ "Torrington Community Hospital",
    `Sequence Group` == "SURG (UCHGH)" ~ "Greeley Hospital",
    `Sequence Group` == "SURG (WOODLAND)" ~ "Pikes Peak Regional Hospital",
    `Sequence Group` == "SURG (WY VA)" ~ "Wyoming Veterans Administration",
    `Sequence Group` == "SURG OP (MHN)" ~ "Memorial Outpatient",
    `Sequence Group` == "SURG OP (SP)" ~ "Summit Pathology Outpatient",
    `Sequence Group` == "SURG OP (SPWY)" ~ "Summit Pathology Outpatient",
    TRUE ~ "Validate_Client"
  )
}
  
  
client_group <- function(`Sequence Group`) {
  case_when(
    `Sequence Group` == "NGYN (BFCMC)" ~ "Banner Health",
    `Sequence Group` == "NGYN (CFG)" ~ "Centers for Gastroenterology",
    `Sequence Group` == "NGYN (CPMC)" ~ "Colorado Plains Medical Center",
    `Sequence Group` == "NGYN (CRMC)" ~ "Cheyenne Regional Medical Center",
    `Sequence Group` == "NGYN (EMCH)" ~ "Banner Health",
    `Sequence Group` == "NGYN (EPMC)" ~ "Estes Park Health Hospital",
    `Sequence Group` == "NGYN (FR DERM)" ~ "Tech Only Clients",
    `Sequence Group` == "NGYN (GRANDVIEW)" ~ "UC Health South",
    `Sequence Group` == "NGYN (HS)" ~ "Melissa Memorial Hospital",
    `Sequence Group` == "NGYN (IMH)" ~ "Ivinson Memorial Hospital",
    `Sequence Group` == "NGYN (JL DERM)" ~ "Tech Only Clients",
    `Sequence Group` == "NGYN (KHS)" ~ "Kimball County Hospital",
    `Sequence Group` == "NGYN (McKee)" ~ "Banner Health",
    `Sequence Group` == "NGYN (MCR)" ~ "UC Health North",
    `Sequence Group` == "NGYN (MHC)" ~ "UC Health South",
    `Sequence Group` == "NGYN (MHCC DC)" ~ "Memorial Hospital of Converse County",
    `Sequence Group` == "NGYN (MHN)" ~ "UC Health South",
    `Sequence Group` == "NGYN (NCMC)" ~ "Banner Health",
    `Sequence Group` == "NGYN (OCH)" ~ "Banner Health",
    `Sequence Group` == "NGYN (PCMH)" ~ "Banner Health",
    `Sequence Group` == "NGYN (PEAK)" ~ "Summit Pathology Outpatient",
    `Sequence Group` == "NGYN (PVH)" ~ "UC Health North",
    `Sequence Group` == "NGYN (RAWLINS)" ~ "Memorial Hospital of Carbon County",
    `Sequence Group` == "NGYN (SRMC)" ~ "Banner Health",
    `Sequence Group` == "NGYN (TORRINGTON)" ~ "Banner Health",
    `Sequence Group` == "NGYN (UCHGH)" ~ "UC Health North",
    `Sequence Group` == "NGYN (WOODLAND)" ~ "UC Health South",
    `Sequence Group` == "NGYN (WY VA)" ~ "Wyoming Veterans Administration",
    `Sequence Group` == "NGYN OP (MH)" ~ "Memorial Outpatient",
    `Sequence Group` == "NGYN OP (SP)" ~ "Summit Pathology Outpatient",
    `Sequence Group` == "NGYN OP (SPWY)" ~ "Summit Pathology Outpatient",
    `Sequence Group` == "SURG (BFCMC)" ~ "Banner Health",
    `Sequence Group` == "SURG (CFG)" ~ "Centers for Gastroenterology",
    `Sequence Group` == "SURG (CPMC)" ~ "Colorado Plains Medical Center",
    `Sequence Group` == "SURG (CRMC)" ~ "Cheyenne Regional Medical Center",
    `Sequence Group` == "SURG (EMCH)" ~ "Banner Health",
    `Sequence Group` == "SURG (EPMC)" ~ "Estes Park Health Hospital",
    `Sequence Group` == "SURG (FR DERM)" ~ "Tech Only Clients",
    `Sequence Group` == "SURG (GRANDVIEW)" ~ "UC Health South",
    `Sequence Group` == "SURG (HS)" ~ "Melissa Memorial Hospital",
    `Sequence Group` == "SURG (IMH)" ~ "Ivinson Memorial Hospital",
    `Sequence Group` == "SURG (JL DERM)" ~ "Tech Only Clients",
    `Sequence Group` == "SURG (KHS)" ~ "Kimball County Hospital",
    `Sequence Group` == "SURG (McKee)" ~ "Banner Health",
    `Sequence Group` == "SURG (MCR)" ~ "UC Health North",
    `Sequence Group` == "SURG (MHC)" ~ "UC Health South",
    `Sequence Group` == "SURG (MHCC DC)" ~ "Memorial Hospital of Converse County",
    `Sequence Group` == "SURG (MHN)" ~ "UC Health South",
    `Sequence Group` == "SURG (NCMC)" ~ "Banner Health",
    `Sequence Group` == "SURG (OCH)" ~ "Banner Health",
    `Sequence Group` == "SURG (PCMH)" ~ "Banner Health",
    `Sequence Group` == "SURG (PEAK)" ~ "Summit Pathology Outpatient",
    `Sequence Group` == "SURG (PVH)" ~ "UC Health North",
    `Sequence Group` == "SURG (RAWLINS)" ~ "Memorial Hospital of Carbon County",
    `Sequence Group` == "SURG (SRMC)" ~ "Banner Health",
    `Sequence Group` == "SURG (TORRINGTON)" ~ "Banner Health",
    `Sequence Group` == "SURG (UCHGH)" ~ "UC Health North",
    `Sequence Group` == "SURG (WOODLAND)" ~ "UC Health South",
    `Sequence Group` == "SURG (WY VA)" ~ "Wyoming Veterans Administration",
    `Sequence Group` == "SURG OP (MH)" ~ "Memorial Outpatient",
    `Sequence Group` == "SURG OP (SP)" ~ "Summit Pathology Outpatient",
    `Sequence Group` == "SURG OP (SPWY)" ~ "Summit Pathology Outpatient",
    TRUE ~ "Validate_Client"
  )
}
